metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.elasticsearch:
  hosts: ["replace_me:9200"]
  ssl.certificate_authorities: ["/etc/certs/http_ca.crt"]
  ssl.verification_mode: none
  protocol: "https"
  username: 'elastic'
  password: 'replace_me'
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
