Vagrant.configure("2") do |config|
    # Define an array of IP addresses
    ips = ["192.168.56.100", "192.168.56.101",
           "192.168.56.102", "192.168.56.103",
           "192.168.56.104"]
  
    # Configure master nodes
    (1..3).each do |i|
      config.vm.define "master-node-#{i}" do |node|
        node.vm.box = "ubuntu/bionic64"
        node.vm.hostname = "master-node-#{i}"
  
        # Configure a private network with a specific IP for each node
        node.vm.network "private_network", ip: ips[i - 1]
        
        # Forward Elasticsearch HTTP port 9200 to a unique port on the host
        node.vm.network "forwarded_port", guest: 9200, host: (9200 + i + 10)
  
        # Forward Elasticsearch internal communication port 9300 to a unique port on the host
        node.vm.network "forwarded_port", guest: 9300, host: (9300 + i + 10)
        
        # Configure VirtualBox specific settings
        node.vm.provider "virtualbox" do |vb|
          vb.name = "master-node-#{i}"
          vb.memory = "512"
          vb.cpus = 2
        end
  
        # Use external script for creating swap file
        node.vm.provision "shell", path: "./scripts/create_swap.sh"
      end
    end
  
    # Configure data nodes
    (1..2).each do |i|
      config.vm.define "data-node-#{i}" do |node|
        node.vm.box = "ubuntu/bionic64"
        node.vm.hostname = "data-node-#{i}"
        node.vm.network "private_network", ip: ips[i + 2]
  
        # Forward Elasticsearch HTTP port 9200 to a unique port on the host
        node.vm.network "forwarded_port", guest: 9200, host: (9300 + i + 30)
  
        # Forward Elasticsearch internal communication port 9300 to a unique port on the host
        node.vm.network "forwarded_port", guest: 9300, host: (9400 + i + 30)
      
        # Configure VirtualBox specific settings
        node.vm.provider "virtualbox" do |vb|
          vb.name = "data-node-#{i}"
          vb.memory = "512"
          vb.cpus = 2
        end
        # Use external script for creating swap file
        node.vm.provision "shell", path: "./scripts/create_swap.sh"
      end
    end
  end
  